{
 "title": "Loki logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Wallet logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"muffin-wallet-wallet\"} |= ``"
    }
   ]
  },
  {
   "title": "Wallet error logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"muffin-wallet-wallet\"} |~ \"error|exception|fail|panic\""
    }
   ]
  },
  {
   "title": "Currency logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"muffin-currency-currency\"} |= ``"
    }
   ]
  },
  {
   "title": "Currency errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"muffin-currency-currency\"} |~ \"error|exception|fail|panic\""
    }
   ]
  }
 ]
}